atoms:
  atom: Rb87
  mass: 1.443160648e-25
mot:
  length: 5.0
beam:
  detuning: 0.0
  linewidth: 6.6
  magnification: 1.0
  wavelength: 780.24602
camera:
  AcquisitionMode: Continuous
  ExposureAuto: 'Off'
  ExposureCompensation: 0
  ExposureCompensationAuto: 'Off'
  ExposureMode: Timed
  ExposureTime: 113.36803436279297
  Gain: 0.0
  GainAuto: 'Off'
  PixelFormat: Mono8
  SharpnessAuto: 'Off'
  TriggerActivation: RisingEdge
  TriggerDelay: 12.159347534179688
  TriggerDelayEnable: false
  TriggerMode: 'On'
  TriggerSelector: FrameStart
  TriggerSource: Line3
camera_info:
  AcquisitionMode: Continuous
  DeviceModelName: Chameleon3 CM3-U3-13S2M
  ExposureMode: Timed
  Height: 964
  RealPixelSize: 3.75
  TriggerSelector: FrameStart
  TriggerSource: Line3
  Width: 1288
cooling:
  cooling_current: 200.0
  cooling_detuninglist:
  - 0.0
  - 0.0
  - 0.0
  cooling_power: 150.0
  cooling_sequence: 3
  cooling_time: 1500.0
  cooling_timelist:
  - 100.0
  - 100.0
  - 100.0
experiment:
  fileformat: bmp
  filename: absorption_imaging_test
  folder: data/
  image_num: 5
  tag: '1'
  wait_time: 2.0
fit:
  center:
  - 650.0
  - 390.0
  fit: true
  fit_2D: true
  fit_optical_density: true
  fix_center: false
  fix_theta: false
  fix_z0: false
  roi:
  - 0
  - 150
  - 1200
  - 800
  roi_enabled: false
  three_roi_enabled: false
  threeroi:
  - 300
  - 300
  - 900
  - 700
  - 400
  - 400
  - 900
  - 700
  - 0
  - 0
  - 200
  - 200
  tof:
  - 3.0
  - 4.0
  - 5.0
  - 6.0
  - 7.0
plot:
  colormap: jet
program:
  author: Yifan
  date: '2018-01-01'
  name: Rb Absorption Imaging
  note: None
  project: f1 state preparation
repump:
  repump_detuning: 0.0
  repump_falltime: 100
  repump_off_time: 200
  repump_power: 9.0
  repump_risetime: 1.0
  repump_time: 1500
  repump_type: normal
unit:
  ExposureDelay: us
  ExposureTime: us
  Gain: dB
  Height: px
  RealPixelSize: um
  TriggerDelay: us
  Width: px
  coil_current: A
  cooling_current: mA
  cooling_detuninglist: MHz
  cooling_power: mW
  cooling_time: us
  cooling_timelist: us
  detuning: MHz
  dispenser_current: A
  linewidth: MHz
  mass: kg
  repump_detuning: MHz
  repump_falltime: us
  repump_off_time: us
  repump_power: mW
  repump_risetime: us
  repump_time: us
  roi: px
  threeroi: px
  tof: us
  wait_time: s
  wavelength: nm
watch_directory: /home/swm/programs/mot_imaging
