atoms:
  atom: Rb87
  coil_current: 0.0
  dispenser_current: 0.0
  mass: 1.443160648e-25
beam:
  crosssection: 3.0
  detuning: 0.0
  linewidth: 6.6
  magnification: 1.0
  wavelength: 680.24602
camera:
  ExposureAuto: 'Off'
  ExposureCompensation: 0
  ExposureCompensationAuto: false
  ExposureMode: Timed
  ExposureTime: 45.59755325317383
  Gain: 0.0
  GainAuto: 'Off'
  SharpnessAuto: Continuous
  TriggerActivation: RisingEdge
  TriggerDelay: 12.159347534179688
  TriggerDelayEnable: false
  TriggerMode: 'On'
  TriggerSelector: FrameStart
  TriggerSource: Line0
camera_info:
  AcquisitionMode: Continuous
  DeviceModelName: Chameleon3 CM3-U3-13S2M
  ExposureMode: Timed
  Height: 964
  PixelFormat: Mono8
  RealPixelSize: 3.75
  TriggerMode: 'On'
  TriggerSelector: FrameStart
  TriggerSource: Line0
  Width: 1288
cooling:
  cooling_current: 200.0
  cooling_detuninglist:
  - 0.0
  - 0.0
  - 0.0
  cooling_power: 150.0
  cooling_sequence: 3
  cooling_time: 1500.0
  cooling_timelist:
  - 100.0
  - 100.0
  - 100.0
experiment:
  ExposureAuto: Continuous
  ExposureCompensation: null
  ExposureCompensationAuto: null
  ExposureMode: Timed
  ExposureTime: 999.0
  Gain: 0.0
  GainAuto: Continuous
  SharpnessAuto: null
  TriggerActivation: null
  TriggerDelay: 208.0
  TriggerDelayEnable: null
  TriggerMode: 'Off'
  TriggerSelector: FrameStart
  TriggerSource: Software
  fileformat: bmp
  filename: f2_ai
  folder: /data/
  image_num: 10
  tag: background
  wait_time: 0.0
fit:
  center:
  - 300.0
  - 400.0
  fit: true
  fit_2D: true
  fit_optical_density: false
  fix_center: false
  fix_theta: false
  fix_z0: false
  roi:
  - 400
  - 300
  - 1100
  - 800
  roi_enabled: false
  three_roi_enabled: false
  threeroi:
  - 300
  - 300
  - 900
  - 700
  - 400
  - 400
  - 900
  - 700
  - 0
  - 0
  - 200
  - 200
  tof:
  - 3.0
  - 4.0
  - 5.0
  - 6.0
  - 7.0
plot:
  colormap: jet
program:
  author: Yifan
  date: '2018-01-01'
  name: Rb Absorption Imaging
  note: None
  project: f1 state preparation
repump:
  repump_detuning: 0.0
  repump_falltime: 100
  repump_off_time: 200
  repump_power: 9.0
  repump_risetime: 1.0
  repump_time: 1500
  repump_type: normal
unit:
  ExposureDelay: us
  ExposureTime: us
  Gain: dB
  Height: px
  RealPixelSize: um
  TriggerDelay: us
  Width: px
  coil_current: A
  cooling_current: mA
  cooling_detuninglist: MHz
  cooling_power: mW
  cooling_time: us
  cooling_timelist: us
  detuning: MHz
  dispenser_current: A
  linewidth: MHz
  mass: kg
  repump_detuning: MHz
  repump_falltime: us
  repump_off_time: us
  repump_power: mW
  repump_risetime: us
  repump_time: us
  roi: px
  threeroi: px
  tof: us
  wait_time: s
  wavelength: nm
watch_directory: /home/swm/programs/mot_imaging/mot_imaging
